services: 
  cs2-mod-server: 
    build: . 
    image: cs2-mod-server
    stdin_open: true
    container_name: cs2-server
    tty: true
    network_mode: "host"
    ports:
      - 27015:27015
      - 27020:27020
    volumes:
      - /path/to/steamcmd:/home/steam/steamcmd
      - /path/to/Steam:/home/steam/Steam
      

